### ISSUE TITLE
BUG Back navigation does not remember type, status and page filters

### ISSUE THREAD

**Issue by yemel** [decentraland/governance#107]
Steps to reproduce:
* Go to https://governance.decentraland.org/?type=poll&status=finished
* Click on the first proposal
* Click on the back arrow right next to the title of the proposal.

**Comment by nachomazzara** [comment]
@schallock we may need to include this one in the next iteration. WDYT?

**Comment by ginocingolani** [comment]
@2fd I'll reopen this since I just repro'ed it.
