### ISSUE TITLE
Fix lists in proposal markdown

### ISSUE THREAD

**Issue by 1emu** [decentraland/governance#1071]
Lists are not showing properly in all proposal fields

The problem seems to be in some formatting we do before sending it to snapshot.

The markdown preview shows a list but after published, the proposal has no line breaks between the list items.

**Comment by andyesp** [comment]
Working now 
![image](https://github.com/decentraland/governance/assets/8242162/8d43c264-51b7-4db9-99a4-807dd05d2f3f)
