### ISSUE TITLE
Automatically add an option to Community Polls to signal invalid questions/answers

### ISSUE THREAD

**Issue by yemel** [decentraland/governance#109]
The front end should automatically generate an option that signals to the creator of the poll that the question was framed incorrectly.

The "Invalid question/options" VP doesn't count towards the threshold of 66% to accept a vote. For example, if 1M mana votes no, 3M mana vote yes, 2M mana vote invalid, that would count as 75% acceptance -- only the 1M of the "no" option and the 3M corresponding to the "yes" option would count.

**Comment by 2fd** [comment]
https://governance.decentraland.org/proposal/?id=b841bb60-e0da-11eb-a20f-d75df7f87ed8
