### ISSUE TITLE
Replace deprecated profile endpoint

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1093]
Hey @gino, also this deprecated endpoint (GET /lambdas/profiles?id=) is being used from governance site. Could you handle this change as well or let me know with whom should I talk? thanks!

**Comment by ginocingolani** [comment]
Related ADR: https://adr.decentraland.org/adr/ADR-226

**Comment by andyesp** [comment]
We are using that endpoint from the `UserMenu` component in the `decentraland-gatsby` lib. We should update the lib version when it's ready.
