### ISSUE TITLE
LAND Owner Badge

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1125]
- The LAND Owner badge is granted to users who own at least 1 LAND in their wallets. 
- The LAND Owner badge will be airdropped to any wallet that has voted at least once in the DAO
- The LAND Owner badge will be airdropped to a wallet after they voted at least once in the DAO (This could be done with a predefined cadence, it doesn't have to be instantly)
- If the wallet does not hold a LAND anymore, the badge will be disabled
- If the wallet owns a LAND after their badge got disabled, they will have to at least vote once in the DAO to have it again (New or enable TBD)

**Comment by heyimjuani** [comment]
Options, from left to right:
- shovel
- pin
- flag

I'd go with the shovel. Thoughts?

![Image](https://github.com/decentraland/governance/assets/467712/618faa69-3930-4f0f-bcb4-bb0c49d4a926)

**Comment by ginocingolani** [comment]
I like the flag, I think it's easier to understand than the shovel. But I don't have a strong opinion on any of them.

**Comment by heyimjuani** [comment]
https://www.dropbox.com/scl/fi/gfus4a1pq3aft0fsjkov4/badge_land.png?rlkey=furqfqnxdhkrk29hcr50q0451&dl=0



![Image](https://github.com/decentraland/governance/assets/467712/669c1b2f-0f2c-4e19-a1cc-4c1681679609)
