### ISSUE TITLE
Legislator Badge

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1126]
- The Legislator badge is granted to users who created at least one Governance proposal that got approved by the Community
- The Legislator badge is granted to the author and the coauthors of the Governance Proposal
- The Legislator badge will be airdropped to any wallet that has voted at least once in the DAO
- The Legislator badge does not expire or gets disabled
- It would be good to take into consideration when building the spec to see if the badge can be upgraded (Created 1, Created 10, Created 25, etc). If not, we can use different specs.

**Comment by andyesp** [comment]
https://www.dropbox.com/scl/fi/qg0l2gwix6iasxea2g1fr/badge_legistator.png?rlkey=1uzjhwtim9p7l8awhoxbosput&dl=0

![Image](https://user-images.githubusercontent.com/467712/258870488-dd6a5aba-afb4-49a3-875b-7ff30a3d1e7e.png)
