### ISSUE TITLE
Top Voter Badge

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1128]
The Top Voter badge is granted to users who were the ones that casted more votes in the DAO at any given month
The Top Voter badge will be airdropped to users who voted with +5VP in the last month (If any of their votes in the target month were with less than 5VP, that shouldn't count)
The Top Voter will be granted the first calendar month of the following month after the votes were casted
The Top Voter badge will either: Be disabled after the following calendar month after the votes were casted or stay active and another Badge will be created for the next month
The Top Voter badge should state in the metadata the month when the votes were casted

**Comment by heyimjuani** [comment]
https://www.dropbox.com/scl/fi/tfaqz9pyzudkp4xhp41vo/badge_top-voter.png?rlkey=ngopy7wxc8y3zmc0ikzz0ojh6&dl=0

![Image](https://github.com/decentraland/governance/assets/467712/c4b7ef28-a79c-4b40-b8b3-8edf0f04d0b3)
