### ISSUE TITLE
Understanding How to Run Gatsby in a Production Setting

### ISSUE THREAD

**Issue by Slyracoon23** [decentraland/governance#1154]
## Description
I've been working on a project where I use Gatsby for the frontend and a separate backend, each running independently in a development setting. However, I'm having trouble understanding how this would work in a production setting.

## Code and Configuration
In my workflow, I use npm run build to compile my frontend source code, which is placed in the /public directory. The backend is compiled to /lib.
```
npm run build
```

I've been looking through the server code but it doesn't seem to serve /public/index.html, which I would expect for the Gatsby app to run properly.

## Issue
On inspecting the server code, it appears that the server doesn't serve the main entry point file /public/index.html which is expected for a Gatsby application to load and run properly.

## Request for Guidance
Could anyone provide guidance on setting up and running a production Gatsby application, especially in a scenario where the frontend and backend are separate?

Should there be additional configuration in the server code to serve the /public/index.html or is there a different approach that is recommended for a production setting?

Thanks for your assitance!

**Comment by andyesp** [comment]
Hi @Slyracoon23, what you ask exceeds the purpose of this project but I'll try to guide you.
Regarding the issue, the server actually serves the compiled Gatsby application here https://github.com/decentraland/governance/blob/master/src/server.ts#L110 and this code is production-ready.

If the frontend and backend are separated then you need to deploy those apps separately. You can check how to deploy a Gatsby app [here](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/). If your backend is a Node.js app then you can try a service like Render or Heroku, after deploying your app they will give you a URL that you can fetch from your frontend.

I don't know what you are building but I recommend you to also check frameworks like Next.js or Remix.
I hope you found this useful.
