### ISSUE TITLE
Add sorting to proposals

### ISSUE THREAD

**Issue by schallock** [decentraland/governance#116]

**Comment by yemel** [comment]
<img width="810" alt="Screen Shot 2021-11-23 at 15 44 04" src="https://user-images.githubusercontent.com/279449/143084965-e5477b7e-b3c5-4b1a-a2aa-fe86950ae15b.png">

Allow the sorting of proposals by LATEST and PARTICIPATION. Latest sorts by date and Participation by total VP that voted.

**Comment by ginocingolani** [comment]
Solved by https://github.com/decentraland/governance/pull/147
