### ISSUE TITLE
Vesting Review Smart Contract link is broken

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1181]
https://vesting.decentraland.org/#/0xbd4c2c464ffc304069856df4f69961e26f3fafb4

![Image](https://user-images.githubusercontent.com/2858950/257332171-bf1ef8f6-9800-41a5-b2bb-81651a571582.png)

It links to undefined

![Image](https://user-images.githubusercontent.com/2858950/257332242-559cadee-5f16-40c3-b017-1248a6ffbb67.png)

**Comment by ncomerci** [comment]
Env vars were not set properly
