### ISSUE TITLE
Verified partners badge

### ISSUE THREAD

**Issue by ncomerci** [decentraland/governance#1185]

**Comment by heyimjuani** [comment]
https://www.dropbox.com/scl/fi/6vk20mxah5iof56a7atbe/badge_studios.png?rlkey=yo18xn8ln6iz7a14bkirz4h8m&dl=0

![Image](https://github.com/decentraland/governance/assets/467712/eec3112a-166d-4e86-aad9-e3102abecd25)

**Comment by ncomerci** [comment]
Done
