### ISSUE TITLE
Create DAO treasury dashboard

### ISSUE THREAD

**Issue by schallock** [decentraland/governance#119]

**Comment by yemel** [comment]
here a few ideas

![Group 26 (1)](https://user-images.githubusercontent.com/279449/132705218-d6d91ba6-12c8-4a90-bbd5-4826955746d4.jpg)

**Comment by maraoz** [comment]
I was about to propose this in the DAO, glad it's already in the roadmap! 

I wanted some sort of UI to see the movements in the gnosis multisig too, for transparency.
Maybe the new tab can be called Transparency instead of Treasury?

**Comment by maraoz** [comment]
I meant this gnosis multisig: https://gnosis-safe.io/app/#/safes/0x89214c8Ca9A49E60a3bfa8e00544F384C93719b1/transactions
