### ISSUE TITLE
Wide(r) single proposal view

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1278]
Part of https://github.com/decentraland/governance/issues/1263

https://www.figma.com/file/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?type=design&node-id=4759-681&mode=design

![Image](https://user-images.githubusercontent.com/467712/269081909-5e565afa-98af-4efa-9064-0b3396ad0298.png)

- Columns on both sides have fixed width
- Center (content) column is fluid
- Optional: we may want to increase font-size + line-height on content (screenshot is using bigger text)

**Comment by ginocingolani** [comment]
Definitions:

- [ ] Columns on both sides have fixed width
- [ ] Center (content) column is fluid
- [ ] Font size increase based on breakpoints for proposal body (Guane to define)
- [ ] Fixed font size for proposal title (Guane to define)
- [ ] Details widget on the left column only on bigger viewports (If not, move to the usual place, below the voting module on the right column)
- [ ] Global tabs instead of breadcrumbs on the hero
- [ ] Colored hero for active proposal and grey hero for finished proposals (Guane to check accessibility contrast ratio)

**Comment by 1emu** [comment]
Creating a different issue for: Details widget on the left column only on bigger viewports (If not, move to the usual place, below the voting module on the right column)

**Comment by 1emu** [comment]
Agreed to keep font size with Guane

**Comment by ncomerci** [comment]
https://github.com/decentraland/governance/pull/1287
