### ISSUE TITLE
Wide(r) homepage

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1279]
https://www.figma.com/file/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?type=design&node-id=13138-1077&mode=design

![Image](https://user-images.githubusercontent.com/467712/269050684-f9700d54-4938-414c-bfae-edecdcc94705.png)

- Max container-width: 1410
- KPI cards are "fluid"
- Open proposals take up the whole width; category + graph/threshold form an imaginary container that has fixed width; the rest of the content on the left has fluid width so that the title gets more px
- Active community grants are "fluid"
- DAO Delegates takes up the whole width; columns/indicators are all floated to the right; avatar + account name take up the remaining space
- Community engagement: modules are fluid but keep the same relation in terms of width

**Comment by ncomerci** [comment]
https://github.com/decentraland/governance/pull/1287
