### ISSUE TITLE
Wide(r) proposal listing view

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1280]
https://www.figma.com/file/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?type=design&node-id=13138-1077&mode=design

![Image](https://user-images.githubusercontent.com/467712/269053285-ee163f3a-1afc-4ffe-859e-df72072ef18f.png)

- Filter/sidebar/left column has fixed width
- Right column/container takes up the remainder of the screen
- Proposal cards are fluid
- Proposal cards are an instance of the ones used on the homepage (view screen below) so layout changes a bit

![Image](https://user-images.githubusercontent.com/467712/269053849-c9b41c7b-e402-4c48-8610-d7f189a37bf7.png)

**Comment by ginocingolani** [comment]
Definitions:

- [ ] Filter/sidebar/left column has fixed width
- [ ] Right column/container takes up the remainder of the screen
- [ ] Proposal cards are fluid

- [ ] Proposal cards are an instance of the ones used on the homepage (view screen below) so layout changes a bit:
- [ ] Can we style the ending timestamp when the proposal ends in less than 24 hours different? @heyimjuani 
- [ ] For money-related proposals (Grants or bid projects) can we make use of the wider real estate to show the # of money requested somewhere? @heyimjuani

**Comment by ncomerci** [comment]
https://github.com/decentraland/governance/pull/1287
