### ISSUE TITLE
Wide(r) proposal scroll down heading

### ISSUE THREAD

**Issue by 1emu** [decentraland/governance#1291]
Part of #1263 

new scroll down interaction: display a new heading

**Comment by 1emu** [comment]
@heyimjuani 

- we need to think what to do with the proposal details and the banner, it looks funny. Also
- is it ok with no shadow at all? 
- shown should it appear/disappear? 


![Image](https://github.com/decentraland/governance/assets/2858950/15af2321-c656-4312-b1ed-c8d1fad22d4b)

**Comment by heyimjuani** [comment]
The bar is to have some sort of white shadow to make it seem as if the content fades away underneath. Like so.


![Image](https://github.com/decentraland/governance/assets/467712/24088d46-953f-48b1-a944-ed5e05993e75)


Proposal details and voting should of course be displayed in their entirety, so they should be positioned accordingly.

Can you set a threshold for this new heading to be displayed only after the user has scrolled X px away from the very top?

**Comment by ncomerci** [comment]
https://github.com/decentraland/governance/pull/1287
