### ISSUE TITLE
Fix profile badges display when there's only one past badge (and no current)

### ISSUE THREAD

**Issue by 1emu** [decentraland/governance#1321]
![Image](https://github.com/decentraland/governance/assets/2858950/51dfdf04-230b-4f71-b9a5-441f49320c2c)

### Reproduction steps
* Go to this user profile https://governance.decentraland.org/profile/?address=0x613e052555ac74ff6af0fc64e40e8035c1e9dcf8

**Comment by andyesp** [comment]
Maybe we should have a design for this? @ginocingolani @heyimjuani

**Comment by heyimjuani** [comment]
If no current badges + 1 past badge = change text to "1 past badge"
If no current badges + x past badges = display up to 3 badges + change text to "x past badges"

![Image](https://github.com/decentraland/governance/assets/467712/9747231d-b981-4fb4-81ab-843b7fd1e818)

**Comment by ginocingolani** [comment]
I think it would be better to not display any badge and just show a "View expired badges" link under the username
