### ISSUE TITLE
Priority widget in Proposal listing view

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1331]
Homepage module

![Image](https://github.com/decentraland/governance/assets/467712/332e196e-b562-4b45-92d4-46b37d1037bd)

Proposal listing module
![Image](https://github.com/decentraland/governance/assets/467712/cb13b03b-ff4a-4ce2-ae6d-b4220ddd4f26)

Specs

- Naming: Important Proposals
- Surface area: Widgets in Homepage and Proposals Listing view
- Behavior: The widget will appear every time a Proposal considered as important is available for DAO Community members to take action.
- Widget will surface proposals from the Governance and B&T Proposals
- Proposals will surface on the widget based on this criteria:
- Governance: Open voting period
- Pitch proposals: Ended pitches with open submission Tender periods (That means, after the first Tender has been published)
- Tender proposals: Ended Tenders with open submission Bid periods
- Bid Proposals: Open voting period

TBC
- Widget in proposal listing view will hide Important proposals in which the user has acted upon. That means:
- Governance: User has voted on the proposal
- Pitch: User has submitted a Tender proposal
- Tender: User has submitted a Bid proposal
- Bid: User has voted on a bid proposal (TBC: If the user voted on one of the open bids for the same Tender, should we hide all of them or just the one the user voted on?)

**Comment by 1emu** [comment]
Use chevron from proposals list 👁

**Comment by 1emu** [comment]
@ginocingolani @heyimjuani I'm gonna need the copy for the info text next to "time sensitive"

**Comment by 1emu** [comment]
Notes:

- Keep the show/hide status across navigation

**Comment by ginocingolani** [comment]
Copy for the widget

| Case | Copy |
|--------|--------|
| active governance | Voting ends in TS |
| open_pitch | Open for Tenders |
| pitch_with_submissions | Tender submission ends in TS |
| pitch_on_voting_phase | Tender proposals voting ends in TS |
| open_tender | Open for Bids | 
| tender_with_submissions | Bids submission ends in TS | 
| active bids | Bid proposals voting ends in TS | 
| priority_homepage_title | Priority Proposals Spotlight | 
| priority_homepage_description | Your vote matters. This section highlights binding Governance and project-related proposals that need your attention now.| 
| priority_proposals_title | Priority Proposals Spotlight | 
| priority_proposals_helper | This section highlights binding Governance and project-related proposals that need your attention. |
