### ISSUE TITLE
Metamask button on mobile should open Metamask app or Wallet Connect modal

### ISSUE THREAD

**Issue by andyesp** [decentraland/governance#1352]
- [ ] Metamask option should deeplink to Metamask app if installed
- [ ] Check if Coinbase option deeplinks to Coinbase wallet if installed
- [ ] I had issues when choosing Metamask when using WalletConnect (But that might be WC issue, not ours)

**Comment by ginocingolani** [comment]
https://github.com/decentraland/governance/assets/5439712/bf06b634-6884-4a38-9a6c-b5f633d7ee4b
