### ISSUE TITLE
Update hover effect in the `Navigation` component

### ISSUE THREAD

**Issue by Petrosdevri** [decentraland/governance#1355]
I would like to update the hover effect in the `Navigation` component because it will improve the User Experience. When you point to a link in the Navbar it doesn't show any effect, which leaves room for improvements.

In my opinion, we can add an underline similar to the one in the active link.

**Comment by ginocingolani** [comment]
Hi @Petrosdevri, thanks for taking the time to open this issue! 
This is a component that we share between multiple dApps, but yours is a good suggestion. We will let you know if we make the change and is approved.

**Comment by ginocingolani** [comment]
We will send a PR to https://github.com/decentraland/ui

**Comment by andyesp** [comment]
We should update decentraland/ui in governance.
