### ISSUE TITLE
Add vesting contract status to Grant widget on profile view

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1382]
Currently, there is no simple way to read the status of a vesting contract attached to a Grant on the user profile:
<img width="1317" alt="Screenshot 2023-10-31 at 11 37 35" src="https://github.com/decentraland/governance/assets/5439712/1708ad4b-889e-4262-a3cb-409153f265ee">

It would be useful to add a label displaying the status of the contract in-context (Active, finished, paused, revoked)

**Comment by heyimjuani** [comment]
Here's my proposal:
- project status below title
- change in "active" status naming → proposal: **WIP**, think it's clearer
- changes in copy to provide a concise summary → each status would have its own
- progress bar present only when project is not finished
- changes in progress bar coloring. 1. yellow indicates vested; 2. funds released has a dynamic color: green for healthy projects (WIP, finished); red for unhealthy (paused/revoked)

![Image](https://github.com/decentraland/governance/assets/467712/f222bf4d-f95e-447a-8f70-647956f3f529)

**Comment by andyesp** [comment]
Closed by #1579
