### ISSUE TITLE
Fix: make smaller font size of the labels and move text to next line on propasal detail actions

### ISSUE THREAD

**Issue by oliviel** [decentraland/governance#141]
The labels are too big and the text is not looking good and with the CSS style text-overflow ellipsis I think you lose valuable information so I suggest moving the text to the next line for resolutions between 768px - 1024px.

This is how it looks now:
<img width="229" alt="Screen Shot 2021-11-28 at 2 00 20 PM" src="https://user-images.githubusercontent.com/16074043/143780096-3c05602d-1e72-4296-9e7e-bac1644df266.png">

<img width="202" alt="Screen Shot 2021-11-28 at 2 00 42 PM" src="https://user-images.githubusercontent.com/16074043/143780112-116c6edc-f994-4fa9-b6f3-bdf9d386c92d.png">

<img width="217" alt="Screen Shot 2021-11-28 at 2 01 27 PM" src="https://user-images.githubusercontent.com/16074043/143780148-b432e5b7-b257-48ea-a740-8677c7b202c8.png">

**Comment by andyesp** [comment]
WDYT @heyimjuani ?

**Comment by andyesp** [comment]
We already made some changes, this is how it looks now
<img width="231" alt="image" src="https://user-images.githubusercontent.com/8242162/225905266-14d699d6-916f-436b-90bf-40e87433799e.png">

**Comment by andyesp** [comment]
I'll close this as we already improved how the information is displayed.
