### ISSUE TITLE
Pop Up Discord Notifications launch

### ISSUE THREAD

**Issue by 1emu** [decentraland/governance#1520]
Pop up should appear to users who have not already connected their accounts. Pop up is dismissable. If the pop up gets dismissed, the message should live as a banner (Same component as the Newsletter and DAO Delegation)

Title: Receive DAO Notifications in Discord!
Body: Connect your Decentraland and Discord in one click! By linking your accounts, you can receive real-time, governance-related notifications directly in your Discord.. Stay in the loop and never miss out on important updates and opportunities to participate.

CTA: Link your Discord account

https://www.figma.com/file/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?type=design&node-id=14914-3102&mode=dev
![Image](https://github.com/decentraland/governance/assets/467712/b64d41d0-c6ab-463f-9933-9900e2dc6f78)

![Image](https://github.com/decentraland/governance/assets/467712/cd8ad7ec-4450-40c7-9f43-c3e49e19ece5)
https://www.figma.com/file/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?type=design&node-id=14953-2574&mode=dev

**Comment by andyesp** [comment]
Closed by #1526
