### ISSUE TITLE
Link passed Bid proposals to Vesting Contracts

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1621]
Currently Bid proposals do not support the attachment of a Vesting contract like Grant proposals do.

At the proposal view:
- [x] Add the Enact buttons for DAO Committee members
- [x] Add Vesting Contract widget like in enacted Grant proposals
![Image](https://github.com/decentraland/governance/assets/5439712/703b80c4-6678-419c-bb5f-00a8b309706e)

**Comment by andyesp** [comment]
Closed by #1630
