### ISSUE TITLE
Notification for comments posted in a proposal

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1623]
Currently, we are creating user activity events for comments published in a proposal.
This issue is about sending those events in the form of notifications (In-app and Discord)

Title: New Comment posted on Proposal "TITLE"
Description: Engage in a productive conversation by replying to this comment.

Target: Proposal author & coauthor

**Comment by 1emu** [comment]
respecto al link: a la proposal. Si tenemos un anchor para ir a la seccion de comments, genial. Sino a la proposal
respecto al iconito: usaria el que usamos en el activity ticker
