### ISSUE TITLE
Replace the Twitter card on the account linking modal and add the Push card

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1716]
Currently the account linking modal does not display Push as an option, and shows Twitter as a Coming Soon.
Let's replace the Twitter card with the Push one.

Order:
Discourse
Discord
Push

Copy
Push Protocol
Receive notifications in your wallet or on any platform using this native web3 communications protocol

**Comment by heyimjuani** [comment]
<img width="578" alt="image" src="https://github.com/decentraland/governance/assets/467712/fd26ea3c-24ab-4403-bf90-9e3b1277b1c8">

https://www.figma.com/file/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?type=design&node-id=15714-4013&mode=dev

**Comment by andyesp** [comment]
Clicking Push card triggers the message signing flow automatically

Pop up in the background:
Title: Subscribe to Push Notifications
Body: Sign the message request with your wallet to subscribe to the DCL DAO Push Notifications channel
Button: Signature Pending/Retry

Success:
Title: Push Notifications enabled successfully!
Body: Now you will receive Governance-related notifications in your Push account.
Button: Connect other accounts

**Comment by andyesp** [comment]
![Image](https://github.com/decentraland/governance/assets/8242162/1362517a-cb89-4889-9e82-097262b02487)
