### ISSUE TITLE
Add a new notice banner on the Proposals page

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1717]
Add a new banner on the Proposals page
Title: Stay Updated, Wherever You Are
Body: Connect your Discord and Push accounts to receive real-time notifications about the latest news in the Decentraland DAO.
CTA: Connect Your Accounts

**Comment by heyimjuani** [comment]
<img width="1504" alt="image" src="https://github.com/decentraland/governance/assets/467712/4faa7c2d-33c3-4e95-9d25-8d5e29b30873">
https://www.figma.com/file/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?type=design&node-id=15687-3268&mode=dev

**Comment by andyesp** [comment]
@ginocingolani @heyimjuani  What is the action of the CTA?
