### ISSUE TITLE
Add a toast to prompt users to link their accounts

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1718]
Title: Stay Updated, Wherever You Are
Body: Connect your Discord and Push accounts to receive real-time notifications about the latest developments in the Decentraland DAO.

CTA: Connect Your Accounts

**Comment by heyimjuani** [comment]
<img width="423" alt="image" src="https://github.com/decentraland/governance/assets/467712/55476708-3be3-4842-be0b-e08decb2793e">
https://www.figma.com/file/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?type=design&node-id=15715-4039&mode=dev
