### ISSUE TITLE
Trigger the account linking modal from the Governance Profile's gear button

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1720]
Change settings/gear button to Linked Accounts button (We will change the Gear icon for a button with a label. Icon TBD. Use Gear until then.)

**Comment by heyimjuani** [comment]
<img width="642" alt="image" src="https://github.com/decentraland/governance/assets/467712/d825f6ef-5c9a-4924-a01d-3d5a67419478">

<img width="583" alt="image" src="https://github.com/decentraland/governance/assets/467712/f60f1ec8-e487-489b-982d-55c966c6a47a">

<img width="576" alt="image" src="https://github.com/decentraland/governance/assets/467712/bdbb989c-cc55-40fa-a623-eaffead57374">
