### ISSUE TITLE
Grant Proposals: Milestones

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1765]
- We will modify the Roadmap section on the Grant Proposal form for the new Milestones section
- Milestones will have a UI similar to team members or budget
- Milestones will have a title, a date, and tasks (or free form text)
- We will send to Snapshot the milestones titles with the date

**Comment by andyesp** [comment]
- Are we ok with this description? Is it going to be tasks or free form text?

**Comment by ginocingolani** [comment]
@andyesp @heyimjuani As per our conversation last week it should be like this:
Milestones will have a title, a date, and a description in free form. That's it.

Do we agree?
