### ISSUE TITLE
Projects widget on Profile

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1875]
Rename "Grants Beneficiary" section to "Projects"

Add to the mouseover helper: 
Vested: $X
Released: $X

Add the role: 
Author: Proposal author
Coauthor: Proposal coauthor
Member: If the user is not author or coauthor of the proposal and the wallet address is defined on the Personnel section

**Comment by 1emu** [comment]
![Image](https://github.com/decentraland/governance/assets/2858950/f2b1eef7-b962-495e-8361-ab2fcefbd89d)

**Comment by heyimjuani** [comment]
https://www.figma.com/design/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?node-id=17091-2683&m=dev

![Image](https://github.com/decentraland/governance/assets/467712/2c674fc4-efb8-43c4-9479-92becf02f967)
