### ISSUE TITLE
Unlink Discord & Forum accounts

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1876]
disabling triggers confirm modal
confirm modal copy TBD
active services first

![Image](https://github.com/decentraland/governance/assets/467712/ab515ca1-1dd4-459b-9447-c62e92c5cf7a)

**Comment by ginocingolani** [comment]
@heyimjuani Since the idea is for the user to unlink the account, I don't feel the switch is the best affordance. It feels like it's just a disable. Maybe we could use a text link stating Unlink? or an erase or remove icon?
I think it would be useful to add to the flow a confirmation before executing the action

**Comment by heyimjuani** [comment]
agree. changed UI element to a simple text link.

when clicked, a confirm modal/alert would be nice.

![Image](https://github.com/decentraland/governance/assets/467712/8601464a-afff-499d-8f8c-ded290303c29)
