### ISSUE TITLE
New Notification: Your delegate voted on your behalf

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1884]
This notification should be triggered every time a delegate votes on a proposal
Target: Delegator

EN:
Title: Your delegate voted on the proposal "TITLE"
Body: **See if their vote is aligned** with your vision. You can always override their decision by voting on your own.
Link: Proposal in which the delegate voted.

ES:
Título: Tu delegado votó en la propuesta "TITLE"
Cuerpo: **Verifica si su voto está alineado** con tu visión. Siempre puedes anular su decisión votando por tu cuenta.

CZ:
标题: 您的委托人在提案“TITLE”上投了票
正文: 查看他们的投票是否符合您的愿景。您始终可以通过自己投票来推翻他们的决定。

**Comment by heyimjuani** [comment]
<img width="800" alt="image" src="https://github.com/user-attachments/assets/e21ecdfa-a1f4-4aa8-b789-f867579bef77">

https://www.figma.com/design/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?node-id=16229-3319&m=dev
