### ISSUE TITLE
New Notification: Whale Vote

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#1885]
This notification should be triggered every time a wallet with over 250k VP votes in a proposal
Target: Proposal author & coauthor

EN
Title: A whale voted on your proposal "TITLE"
Body: A wallet holding over 250k VP has just **cast a vote**. Stay informed and see how this significant vote impacts the outcome.

ES
Título: Una ballena votó en tu propuesta "TITLE"
Cuerpo: Una billetera con más de 250k VP acaba de **emitir un voto**. Mantente informado y revisa cómo este voto significativo impacta el resultado.

CZ
标题: 一位鲸鱼对您的提案“TITLE”进行了投票
正文: 一个持有超过25万VP的钱包刚刚投票。保持关注，看看这一重要投票如何影响最终结果。

**Comment by heyimjuani** [comment]
<img width="796" alt="image" src="https://github.com/user-attachments/assets/92561b17-450f-45af-8010-fe0aca5a970f">
https://www.figma.com/design/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?node-id=16229-3319&m=dev
