### ISSUE TITLE
Google Indexing Error

### ISSUE THREAD

**Issue by yemel** [decentraland/governance#195]
One URL is being crawled by Google robots but the server returns 404. The URL must be reported in a sitemap or similar, but the URL is no longer present.

URL with the issue:
https://governance.decentraland.org/submit/poi/

**Comment by ginocingolani** [comment]
We need to remove that one and add
https://governance.decentraland.org/submit/poi/?request=add_poi
https://governance.decentraland.org/submit/poi/?request=remove_poi
