### ISSUE TITLE
Force grant tiers to be enforced

### ISSUE THREAD

**Issue by maraoz** [decentraland/governance#196]
I've seen quite a few of grant proposals where the money requested was greater than the tier-allowed funds.

Examples:
- https://forum.decentraland.org/t/dao-qmrzqcd-building-the-petaverse-park-the-decentraland-experience-for-pet-lovers/9246/4?u=maraoz
- https://governance.decentraland.org/proposal/?id=df4b7520-a08d-11ec-831d-95af4f79cd2a

- https://governance.decentraland.org/proposal/?id=4ad3a8d0-958f-11ec-831d-95af4f79cd2a

- https://governance.decentraland.org/proposal/?id=d7202560-8de8-11ec-9794-c9ea21a9ed8f

- https://governance.decentraland.org/proposal/?id=d78edbe0-80e6-11ec-9166-a5dd0ddb7cdb

Consider adding programmatic checks to the grant submission form. Thanks!

**Comment by ginocingolani** [comment]
**Checks**
Tier 1: <= 1500
Tier 2: >1500, <= 3000
Tier 3: >3000, <= 5000 
Tier 4: >5000, <= 60000 
Tier 5: >60000, <= 120000 
Tier 6: >120000, <= 240000 

If Tier selection doesn't match the defined amount the publication button is disabled and an error message appears.

Error message for higher amount: The amount you are requesting for this grant is greater than the limit defined for the Tier you selected. Please consider lowering the amount or changing the Tier to publish this proposal.

Error message for lower amount: The amount you are requesting for this grant is lower than the limits defined for the Tier you selected. Please consider selecting a lower Tier to publish this proposal.
