### ISSUE TITLE
Show all comments from the forum in the proposal page

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#199]
At the moment we're only showing the latest comments sorted by date from the forum on the Governance dApp. Ref PR: https://github.com/decentraland/governance/pull/159
It would be ideal that once the user clicks on the Read More button, more comments are fetched and displayed on-page.

**Comment by 1emu** [comment]
When user presses 'read more':
- we show all user comments from the forum (this could be a few or several). **
- the 'Read More' button changes to 'Join the Discussion' and links to the forum

Would this be OK?

**A note on performance: The API request always returns the full topic with all the comments, so fetching a few or all of them doesn't make a different (we always get all)

**Comment by ginocingolani** [comment]
If performance is not an issue I agree with showing all the comments at once and changing the button to Join the Discussion
