### ISSUE TITLE
Display finished date on proposal listing and sorting

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#203]
Right now the list only shows the end date of active proposals, it would be useful to also display the end date of the finished proposals.
Ref: https://prnt.sc/k0jWCE7yFtct

**Comment by ginocingolani** [comment]
<img width="857" alt="Screen Shot 2022-03-18 at 12 49 17" src="https://user-images.githubusercontent.com/5439712/159036607-5c72c77e-816a-4198-87fa-2831b9f3505e.png">

**Comment by 1emu** [comment]
http://pr203.test.decentraland.vote/

https://github.com/decentraland/governance/pull/206
