### ISSUE TITLE
Grant tiers refactor

### ISSUE THREAD

**Issue by 1emu** [decentraland/governance#210]
- Separate grant text description from type
- Improve wording to include lower limit (maybe expressing numbers abbreviated with k)

Remember to check for compatibility with saved proposals in the DB

**Comment by ginocingolani** [comment]
@1emu Does it makes sense this card now that we have the new Grants? If not, please 💀 it

**Comment by andyesp** [comment]
We changed how tiers work now. Closing this issue.
