### ISSUE TITLE
Double loader in proposal sidebar

### ISSUE THREAD

**Issue by ncomerci** [decentraland/governance#256]
![image](https://user-images.githubusercontent.com/45410089/163172510-e3e464e6-cbb8-42e6-b21c-f9b871eba001.png)

### Steps to reproduce the bug

- Log out from Governance Dapp
- Go to any proposal
- Sign in and, while Metamask asks for your signature, you will see this double loader

#### Should look like this
![image](https://user-images.githubusercontent.com/45410089/163177015-033764af-9f12-4b4c-98e4-eab9432fa3ae.png)

**Comment by andyesp** [comment]
Fixed with the delegation dashboard changes.
