### ISSUE TITLE
ctrl+click to open proposals in new tab has broken

### ISSUE THREAD

**Issue by maraoz** [decentraland/governance#278]
**Environment**: Windows 10, Brave 1.38.109 Chromium: 101.0.4951.41 (Official Build) (64-bit)

**How to reproduce**:
1. Go to https://governance.decentraland.org/?status=active
2. ctrl+click a proposal's title
3. current tab changes to the proposal's page. no new tab opens.

**Expected result**: 
A new tab opens for each ctrl+clicked proposal 

This behavior was very useful to open all proposals I want to vote on, and then go through all the tabs. Can we get it back? 🙏

**Comment by ginocingolani** [comment]
🤦 Thanks for the report! 
@andyesp @1emu maybe the Gatsby upgrade messed this up somehow. Can we check?

**Comment by maraoz** [comment]
Just in case, please check if you can reproduce the bug. I also fear it migh have been a change in my browser or OS settings. Not sure

**Comment by andyesp** [comment]
Thanks for the report @maraoz, I was able to reproduce the bug in that case and in other pages as well. Pull request created!
