### ISSUE TITLE
Create snapshot and forum template

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/governance#31]
Based on the current forms that will be hosted in governance.decentraland.org. We need to define the template that will end up using markdown or not posted in the Snapshot space and the forum.

**Comment by schallock** [comment]
Copy for the templates: https://docs.google.com/document/d/1onUUjpYrmvXsKhJa7aJ1saPhPss7kMsQTnqVb62tDsw/edit?usp=sharing
