### ISSUE TITLE
Display a warning when users clicks on a link that takes them to an external domain

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#317]
Right now if a user clicks on a link on the description of a governance proposal there is no warning that they might be leaving the Governance/Decentraland domain. We should add an alert for that as a security measure.

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/8242162/224334589-404e15ae-fbac-4e52-bfe5-7872d22dc539.png">

**Comment by heyimjuani** [comment]
Plz change to 

![Image](https://user-images.githubusercontent.com/467712/225642413-c3c8cd80-4fef-49c2-a0a9-9de5d2a4f62a.png)

**Comment by ncomerci** [comment]
Fix addressed in #810
