### ISSUE TITLE
New Home

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#416]
This issue serves as the main parent of all the tasks related to the New Homepage of the DAO Governance dApp

![Image](https://user-images.githubusercontent.com/5439712/179520987-4b83c6cf-cbb4-401c-9d77-5e001f1617e5.png)

Reference: https://www.figma.com/file/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?node-id=5448%3A1837
PRD: https://www.notion.so/dcl-dao/PRD-Governance-New-Home-ed01405dc9314246ad73aed6f50e72a1

A product-centric view breakdown of tasks is listed below. Feel free to add any engineering-related tasks.

### Top Section
- [x] New top level tab (Replaces Proposals tab as the landing. Now proposals is https://governance.decentraland.org/proposals)
- [x] New header card: Links to Docs (https://docs.decentraland.org/decentraland/what-is-the-dao/) and Discord invite (https://discord.gg/amkcFrqPBh)
- [x] Metrics cards: Active Proposals currently + ending soon (Next 48hs). Vote count last 7d + last 30d. Treasury (From Transparency) 

![Image](https://user-images.githubusercontent.com/5439712/179524477-7aad7779-28a0-468a-9f4e-4082a7ff2aad.png)

### Proposal List
- [x] List of up to 5 proposals sorted into three categories accessible by navigation tabs.
Ending Soon: Active Proposals sorted by ending date (Ending sooner at the top)
Participant VP: Active proposals sorted by VP participating in the voting (Higher at the top)
Controversial: Proposals sorted by the smallest delta between options (Only boolean proposals)

![Image](https://user-images.githubusercontent.com/5439712/179525154-4f89c117-4401-477a-ad00-87d3f5b30664.png)

### Grants

- [x] List up to 4 Active Grants sorted by latest update. By doing this we ensure that we're listing Grants that are active currently.

![Image](https://user-images.githubusercontent.com/5439712/179528850-7261d470-aa22-4976-8238-1c3f70cff6b3.png)

### Delegates

- [x] List up to 6 Delegates sorted by Picked by column.

![Image](https://user-images.githubusercontent.com/5439712/179528866-b7f42ea8-f04a-436e-a419-d771f2a5b302.png)

### Engagement

- [x] Line chart with two views: 1. Total amount of participating VP per calendar month. This is calculated by adding up the total amount of VP participating in each vote made on the calendar month. 2. Votes per proposal: Median of votes cast per proposal on a calendar month.

![Image](https://user-images.githubusercontent.com/5439712/179528898-9d8fa429-ebab-4df0-9853-48f29c4ce0a8.png)

### Bottom Card

- [x] Card at the bottom showing links to the Discord server (https://discord.gg/amkcFrqPBh), forum (https://forum.decentraland.org/) and Newsletter subscription (For this we can pop up the modal that we have or direct users to a landing page to subscribe provided by Mailchimp)
- [x] Display KPIs: Funds Granted calculated as the sum of the total amount of enacted grants and Grants funded: Total amount of Grants marked as enacted. 

![Image](https://user-images.githubusercontent.com/5439712/179540232-371ed432-d5da-4903-bf22-df7073d78e0b.png)

**Comment by andyesp** [comment]
@ginocingolani what is the "ending soon" time window in the stats card? 
We think the ending soon counter label should have a different name than the ending soon list (e.g: "10 ending this week"), as the ending soon list will always show the first 5 proposals ordered by finish date and the count will be a count from a specific interval. WDYT?
