### ISSUE TITLE
L1 Wearables Voting Strategy Testing & Enablement

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#497]
Based on this passed [Governance proposal](https://governance.decentraland.org/proposal/?id=16aa0de0-f405-11ec-b5fc-5178246a05ac) L1 Wearables will provide VP to their holders. The VP assigned to each wearable will depend on the rarity of the wearable. 
frami already coded the strategy merged in the snapshot repo [here](https://github.com/snapshot-labs/snapshot-strategies/pull/606)

To test this strategy we will have to reach out to the Wearables VP Working group to ask them to test the strategy in our testing snapshot space. We will also have to warn them that the VP breakdown won't reflect the VP assigned to the wearables so they will have to do the math themselves (This is something that we will implement in the new profile page coming in the next month on the governance dApp)

**Specification**
Attach voting power, distributed by rarity to the six (6) official Decentraland wearable collections released in 2019. This includes:

Community Contest
DCL Launch
Exclusive Masks
Halloween 2019
MCH Collection
Xmas 2019

There are 48,620 wearables in these six collections, spread across 7,583 wallets. This equates to nearly 70% of the 71,082 total L1 wearables spread across 10,442 unique wallets.

VP will be distributed according to rarity as follows:

Mythic: 1000 VP
Legendary: 100 VP
Epic: 10 VP
Rare: 5 VP
Uncommon: 1 VP

There are 644 mythic across 189 unique wallets; 4,249 Legendary across 827 individual wallets; 17,382 Epic across 4,820 unique wallets; and 24,713 rares across 4,126 unique wallets.

**Comment by andyesp** [comment]
Strategy added to "lemu.dcl.eth" testing space. It's working as expected!
