### ISSUE TITLE
Broken user mentions in comment section

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#544]
Migrated from: https://github.com/Decentraland-DAO/transparency/issues/15#issue-1340670346

When a forum comment contains a link to a user, that link leads to a 404: the link should go to /balance/?address=... instead of /u/someone. See for example: the comment on https://governance.decentraland.org/proposal/?id=659ab8a0-18d6-11ed-96c7-2fa07c6df25b

Originally authored by @eordano

**Comment by andyesp** [comment]
![image](https://user-images.githubusercontent.com/8242162/203357384-2d3c82e0-1cfe-4a5b-9ead-6f58007dd703.png)
![image](https://user-images.githubusercontent.com/8242162/203357415-9a77f0be-25d9-4336-9214-1e00bbe6d6e1.png)
