### ISSUE TITLE
Images bigger than container in proposal comments

### ISSUE THREAD

**Issue by andyesp** [decentraland/governance#577]
![image](https://user-images.githubusercontent.com/8242162/196988904-35e8f6e2-a517-4315-8370-9b16f4cf0fc8.png)

**Comment by ef3n9r98** [comment]
Hi @andyesp, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/
).


Thanks!
