### ISSUE TITLE
Splash Page Content and Behaviour

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/governance#58]
- Define carousel content images.
- Define copy.
- Define if we need to show it always or just once.

**Comment by schallock** [comment]
Copy is finished and can be found here: https://docs.google.com/document/d/1SsM8MNLdywu3HRHQ6M5fHfYxR4amLkWAUcx_YB6UEGc/edit?usp=sharing

**Comment by schallock** [comment]
I'm working on defining the image content, and I think that we should plan to show it just once.

**Comment by nachomazzara** [comment]
@schallock  are we going to do this or should we close it?
