### ISSUE TITLE
Proposal: Make the "Get Involved" banner on the home page dismissable

### ISSUE THREAD

**Issue by eordano** [decentraland/governance#612]
It takes up all the above-the-fold screen space to me when I go to the main page. Could we add a little "X" on the top right corner to dismiss it?
![image](https://user-images.githubusercontent.com/42750/204282075-30766e72-8029-4dec-af9b-84e1eefc61c9.png)

This is even more noticeable on mobile

**Comment by andyesp** [comment]
Figma link for this issue in https://github.com/decentraland/governance/issues/613#issuecomment-1346815917
