### ISSUE TITLE
Show Revoked /paused Vesting Contracts

### ISSUE THREAD

**Issue by Zino84** [decentraland/governance#679]
It Would be great if the community could have direct access to see the Grants whose vesting contract was revoked/paused.
Why?
Because if people don´t have access to it, it feels like the information "is lost" and the only squad that could follow the cases up is the Grant Support Squad. 
Although it's their responsibility, it would be beneficial for the whole community to have full visibility of these.

I suggest we show these using a filter in the Dashboard, unless you come up with any other ideas that might be useful according to your expertise in this field.

![Screen Shot 2023-01-06 at 15 15 47](https://user-images.githubusercontent.com/117465474/211073732-7bf53368-2349-4289-b7ed-27990cc8976e.png)

**Comment by andyesp** [comment]
Solved by #698
