### ISSUE TITLE
Analysis: Proposal outcomes and creation against Grant pause & delegation removals

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#717]
After the pause of the Grants program, the number of proposals created reduced significantly, and after the removal of delegated VP from major stakeholders of the community we've seen an increase in the number of proposals rejected for not getting enough VP.
The idea would be to create a graph to inform the community about this with the following axis
X: Time (Last 6 months)
Y: Number of proposals (Double axis: Created and per status)

Two milestones: Grants pause (January 1st, 2023) and removal of high-profile delegations (January 15, 2023)

**Comment by ncomerci** [comment]
Done
