### ISSUE TITLE
Add Tobik to the DAO Committee allowlist

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#797]
After a passed binding Governance proposal, Tobik has been added to the DAO Committee.
We need to add his address to the allowlist.

**Comment by ncomerci** [comment]
Check the following PRs to close this issue:

https://github.com/Decentraland-DAO/transparency/pull/39
https://github.com/decentraland/definitions/pull/219

**Comment by ncomerci** [comment]
Done
