### ISSUE TITLE
Grants: Show URL title on Relevant Link field

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#804]
Retrieve page title from Relevant URL and display it on the Proposal view

![Image](https://user-images.githubusercontent.com/5439712/225061775-164b9b02-6651-45ed-b14c-5b4f8c7b9b67.png)

**Comment by ncomerci** [comment]
@heyimjuani Your request was moved to #841 since it is for another component

**Comment by ncomerci** [comment]
@ginocingolani @heyimjuani How would you like to display the link title in the proposal?

By replacing "Relevant Link" with the title? Showing it in gray on the side? How?

**Comment by heyimjuani** [comment]
Replace "relevant link" text with "page title" text.
