### ISSUE TITLE
Sense of Urgency for about-to-finish Proposals

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#807]
## Problem

Right now there is no visual/UX cue that highlights that the voting timeframe for a proposal is about to end. This could lead to users not casting their votes due to procrastination or analysis paralysis while the proposal is at its last hours/days resulting in less participation and engagement

## Proposal

Adding a visual hint when the proposal is about to end. We should use the same filter that we're using for the Ending Soon section in the DAO Home Widget.

![Image](https://user-images.githubusercontent.com/5439712/225635308-611996b7-8f37-4c3a-9f4d-8af646b43bf4.jpg)

**Comment by andyesp** [comment]
Use same logic as in the proposal preview cards.
