### ISSUE TITLE
Improve helper text on Budget Breakdown field in Grant Request Form

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#815]
Description below Budget Breakdown title:

Please provide a detailed specification on how you will be using the funds requested for this Grant. Our community values transparency, so be as specific as possible.

Helper text below Duration field:
In how many months will this cost be splitted

**Comment by heyimjuani** [comment]
@andyesp splitted is no such a word! Past tense of split is split. 

In how many months will this cost be split

**Comment by ginocingolani** [comment]
hahaha my bad 💅
