### ISSUE TITLE
Show a specific error when a user is connected to a wrong network when using the Vesting Contract page

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#827]
If the user has his hot wallet connected to a network that is not Ethereum mainnet, the page fails to load instead of showing an error hinting to change the network to see the page (Similar to what we do with the Governance dApp)
Ref:

![Image](https://user-images.githubusercontent.com/5439712/226205915-34baa08f-ed09-45c5-ad56-e84e61f9768f.png)

**Comment by andyesp** [comment]
Solved in decentraland/vesting-dashboard#72
