### ISSUE TITLE
Badges v1

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#850]
- Badges will be minted by internal teams
- Badges will be awarded to:
   - DAO Committee 
   - WCC
   - Core Units (GovSquad, GSS, Facilitation Squad)
   - Grantees (Historical. Nice to have: Current grantees)
   - Nice to Have: Verified Studios
 - Badges will be displayed on the user profile
 - Badge holders will be defined on a JSON in Transparency
```
{ badges: [{ name, description, image, addresses: [{ address, created_at (unix timestampz) }] }] }
```

Estimation: 2 working weeks

**Comment by heyimjuani** [comment]
![Image](https://user-images.githubusercontent.com/467712/229229014-6438714f-8655-47f2-a14f-3e146fff35a5.png)

https://www.figma.com/file/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?node-id=5541-955
