### ISSUE TITLE
New Category: Hiring Proposal

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#853]
New Category: Committee Members
- Sub Category: Add Committee Member / Remove Committee Member
6M VP /  Duration: 4 Weeks
Min VP to submit: 2,500VP
Yes/No/Abstain

User will be able to select first the Add/Remove Committee Members and then select if Add or Remove.
Remove category will always be available
If there is no slot available in any committee, user's won't be able to select a committee in the selection dropdown.

Form Structure:
Committee (Select only between Committees with open slots)
Address
Reasons to add/remove
Evidence

Title structure
Should [XXXX](DCL NAME/AVATAR NAME/ADDRESS) be added to [Committee Name]?
Should [XXXX](DCL NAME/AVATAR NAME/ADDRESS) be removed to [Committee Name]?

- [ ] Check Committee availability in Team Transparency JSON

Transparency: JSON file with Committee, addresses associated with that committee and available slots.
- Dao Committee (3)
- Curations Committee (15)
- Revocations Committee (7)
- SAB (5)

@heyimjuani To define icon & color

Estimate: 6 working days

**Comment by heyimjuani** [comment]
https://www.figma.com/file/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?node-id=10025-6866
