### ISSUE TITLE
In-app Notifications V1

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#854]
## v1

- Contract Enacted
Trigger: A member of the DAO Committee mark a passed Grant proposal as enacted by adding a Vesting Contract
Target recipient: Author / Coauthors of the Grant Proposal
Copy: Title: "Grant Proposal Enacted"
Description: "Congratulations! Your Grant Proposal has been successfully enacted and a Vesting Contract was added" 
Target URL: Grant Proposal URL
Type: Grants

- Co-author Request Received
Trigger: A proposal got published and the user has been added as a coauthor.
Target recipient: Proposed co author
Copy: Title: "Co-author Request Received"
Description: "You've been invited to collaborate as a co-author on a published proposal. Accept it or reject it here"
Target URL: Proposal URL
Type: Proposals

- Voting Ended (Authors)
Trigger: A proposal ended
Target recipient: Authors & Co authors of the proposal
Copy: Title: "Voting Ended on Your Proposal [TITLE]"
Description: "The votes are in! Find out the outcome of the voting on your proposal now."
Target URL: Proposal URL
Type: Proposals

- Voting Ended (Voters)
Trigger: A proposal ended
Target recipient: Users who voted on the proposal
Copy: Title: "Voting Ended on a Proposal You Voted On"
Description: "Discover the results of the proposal you participated in as a voter. Your input matters!"
Target URL: Proposal URL
Type: Proposals

- New Feature/Changelog
Trigger: Governance Squad released a new feature
Target recipient: Users of the DAO
Copy: TBD
Target URL: Customized by Governance Squad
Type: Announcements

**Comment by heyimjuani** [comment]
https://www.figma.com/file/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?type=design&node-id=13277-6750&mode=design

![Image](https://github.com/decentraland/governance/assets/467712/7b9013ea-aa84-491f-90e8-fd44c87d7ede)
