### ISSUE TITLE
Performance Improvements (Ongoing)

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#855]

**Comment by ncomerci** [comment]
Research: https://www.notion.so/dcl-dao/DAO-Performance-research-2680f80498594b1c9cc8ba3a0fec3ab3?pvs=4

We are awaiting progress on this PR https://github.com/decentraland/decentraland-gatsby/pull/530

**Comment by andyesp** [comment]
Performance was improved by caching requests done at the home page.
