### ISSUE TITLE
Add link button to Legislative Tracker

### ISSUE THREAD

**Issue by fenhz** [decentraland/governance#866]
Add a link button to the **Legislative Tracker** (https://www.notion.so/dcl-dao/Governance-Legislative-Tracker-Digest-BETA-7a9ef2f2f9d142d39cd7b33391ec97ae?pvs=4) within the **PROPOSALS** section.

**Comment by heyimjuani** [comment]
Copy TBD


![Image](https://github.com/decentraland/governance/assets/467712/7b9bf6b6-844b-45fd-9938-b333ddabd8da)


https://www.figma.com/file/e0IFJjplUdYdQJ2NtLwvMf/DAO-v2-(Guane)?type=design&node-id=13138-4876&mode=dev
