### ISSUE TITLE
Not count votes with <1VP in the Voting module

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#874]
At the moment, on the voting module, we display the # of votes and the total VP for each one of the voting options. Lately, we've been targeted by bots that vote on proposals with fractions of VP just to potentially farm airdrops. But this creates the sensation that many people are voting for something but not getting the VP needed to back their decision.
It would be good to:
- Not count the votes (on the frontend)

![Image](https://user-images.githubusercontent.com/5439712/226018150-fc63e611-3315-4464-a4a6-2b846301d86d.png)

- When the voting modal is open display the bot votes greyed out and differentiate low quality votes

![Image](https://user-images.githubusercontent.com/5439712/226018236-1450c2da-82fd-4cf4-a30b-56e4134edbae.png)

**Comment by heyimjuani** [comment]
@ginocingolani 

Proposed changes:
- remove vote count from partial results when displayed
- remove "hide votes call to action" → replace for "view votes"
- modal shows vote count as it should, but whatever we consider "low quality votes" will be moved to the bottom and "collapsed".
- add button "show low quality votes" at the end of the vote list
- "low quality votes" are grayed out and only displayed after the user clicks on the "show" CTA

![Image](https://user-images.githubusercontent.com/467712/228901658-9b22767e-0e5f-4472-92e4-0dd7b532094c.png)



![Image](https://user-images.githubusercontent.com/467712/228901736-2eb2b59b-7a7c-46a4-af62-286064355de1.png)

****

**Comment by ginocingolani** [comment]
Discussed with @heyimjuani 
We will showcase the vote count, we will only hide low quality votes from that count.

**Comment by ginocingolani** [comment]
Button to load 'low quality votes': Show votes with less than 5VP
