### ISSUE TITLE
Projects Dashboard

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#901]
- New tab: Open Tenders
- Bids can be submitted to Approved Tenders
- The bidding period duration: 1 month.

**Comment by heyimjuani** [comment]
**Proposed change of scope:**
- no new tab;
- change "grants" to "projects"
- "projects" page allows for browsing of both kinds of initiatives
- "opportunities" are shown on the Governance homepage
- "opportunities" also shown in Proposals feed
- passed tenders allow for Bid submission


![Image](https://github.com/decentraland/governance/assets/467712/b3d4847a-ff59-41c5-9aa0-96a8b113bda6)


![Image](https://github.com/decentraland/governance/assets/467712/8bcbc752-b96d-4637-8a4a-5db6212c9668)


![Image](https://github.com/decentraland/governance/assets/467712/6c286a7f-bc0e-4585-aee8-c7ee3793fafa)


![Image](https://github.com/decentraland/governance/assets/467712/a403f88e-d269-4540-993b-3fa7b38580be)


![Image](https://github.com/decentraland/governance/assets/467712/37505c7b-04b2-4e2c-bef6-27800ed59e39)

**Comment by heyimjuani** [comment]
Updates:
- to be decided: collapse huge hero module into a lighter bar
- selected project type has a slightly tinted background color + change in icon
- project cards have a component that changes with context
- project cards look a bit different (grants vs b&t)
- darker cards at the have information that changes depending on context
- darker card to the very right allows for browsing. Desire: when browsing "all projects", clicking on it will open side panel showing proposals that would result in funding that are open (grants + tenders open for bids and/or bids open for vote)
- if filtering by Grant category, use the category color on the dot to suggest selected category

Future desire:
- Different status affect information displayed on the darker blocks

![Image](https://github.com/decentraland/governance/assets/467712/ec125465-ecf0-4a71-9c9b-c0eae07dcfd7)



![Image](https://github.com/decentraland/governance/assets/467712/2aea7f41-3dfe-4e40-8463-1491eca163b5)



![Image](https://github.com/decentraland/governance/assets/467712/0029cc55-f1c1-415e-88f4-3ae2106f076f)





![Image](https://github.com/decentraland/governance/assets/467712/9c54f3e3-b229-4412-99f6-87a20473f5b2)




![Image](https://github.com/decentraland/governance/assets/467712/96fecffb-6436-44f1-827a-4a48ac9a9463)
