### ISSUE TITLE
Grant category is not visible on enacted proposals

### ISSUE THREAD

**Issue by andyesp** [decentraland/governance#923]
Active:

![Image](https://user-images.githubusercontent.com/8242162/232105345-72c98ced-601b-4ffd-b8ba-421083b913b6.png)

Enacted:

![Image](https://user-images.githubusercontent.com/8242162/232105376-7e5898a5-c5df-4789-99a2-7bc771bed5cc.png)

**Comment by ginocingolani** [comment]
On enacted Grants:
- Past tense: Requested (Instead of requesting)
- Bar graph shows the % of requested funds over the total category budget
