### ISSUE TITLE
Competing v2

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#931]
changes:
- remove contested percentage
- available is moved to the upper line. available hint/reference is rectangular!
- add 100% with those markers at the end of the available line in the graph
- remove "over budget" indicator
- "this initiative" active part of the graph is 10px height and solid red color (same user for contested + available reference) 

![Image](https://user-images.githubusercontent.com/467712/232817006-69b90204-5837-41f0-9f7a-204b60e7f75c.png)

**Comment by heyimjuani** [comment]
![Image](https://github.com/decentraland/governance/assets/467712/058e3c09-d337-4abe-8c0e-214655d1a4a4)
also plz change information on the second line, below the name, to:
- avatar
- money requested
- VP count for yes (x) over pass threshold (y); syntax: x/y
- ends in z days


desired (with colors)
![Image](https://github.com/decentraland/governance/assets/467712/38e8f9f3-9eb2-497e-841c-5b1f8483a1a3)

(this would be acceptable as well)
![Image](https://github.com/decentraland/governance/assets/467712/9ff4888f-c5ee-4e9f-9af2-8de093bc4be0)
