### ISSUE TITLE
Tag Revenue generating transactions from DAO Grants in Transparency

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#972]
Based on this addresses: https://docs.google.com/spreadsheets/d/176GeTmGzHodgzv6KuGtM4PxwcOrgR_KHuhzU_MSdyM4/edit#gid=1259716385

It would be nice if we find a way to make this as self service as possible so the GSS can update the addresses without our assistance.

**Comment by giacastello** [comment]
Glad to help with insights if needed!
